apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nginx-service","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"nginx-deployment"},"type":"LoadBalancer"}}
  creationTimestamp: "2022-09-23T13:49:36Z"
  name: nginx-service
  namespace: default
  resourceVersion: "3063631"
  uid: 7d035e33-9cab-4bee-83ae-6e262b90a50e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.180.136
  clusterIPs:
  - 10.106.180.136
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30824
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deployment
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
