
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  template:
    metadata:
      labels:
        app: postgres-container
    spec:
      containers:
        - name: postgres-container
          image: postgres:11
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: django-k8s-web-prod-env
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-k8s-web-prod-env
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: django-k8s-web-prod-env
                  key: POSTGRES_USER
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: django-k8s-web-prod-env
                  key: POSTGRES_PORT

          ports:
            - containerPort: 5434
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc

---

kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-container
  ports:
    - protocol: TCP
      port: 5434
      targetPort: 5434